#!/bin/bash
#
# Configure Script for Login Server
#
# Run this _BEFORE_ you run "make"
#
# @author: RageD (Dennis J. McWherter, Jr.)

TOTAL=2
CUR_PATH=`dirname $(readlink -f "$0")`

echo "Collecting environment variables necessary for compilation..."
echo "[1/$TOTAL] Getting current directory..."
echo "[2/$TOTAL] Writing include/LocalDefinitions.h..."

### BEGIN WRITING FILE ###
echo "// File automatically generated by configuration script. DO _NOT_ edit this file unless you are absolutely certain of what you are doing" > $CUR_PATH/include/LocalDefinitions.h
echo "" >> $CUR_PATH/include/LocalDefinitions.h
echo "#ifndef __LOCAL_DEFS_H__" >> $CUR_PATH/include/LocalDefinitions.h
echo "#define __LOCAL_DEFS_H__" >> $CUR_PATH/include/LocalDefinitions.h
echo "" >> $CUR_PATH/include/LocalDefinitions.h
echo  '#define PATH_TO_LOGIN "'$CUR_PATH'"' >> $CUR_PATH/include/LocalDefinitions.h
echo  "#define LOGIN_SERVER" >> $CUR_PATH/include/LocalDefinitions.h
echo  "" >> $CUR_PATH/include/LocalDefinitions.h
echo  "#endif" >> $CUR_PATH/include/LocalDefinitions.h
### END WRITING FILE ###

echo "Done!"
